# Generated by Django 3.2 on 2021-06-20 05:56

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('value', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique_for_date=datetime.timedelta(days=30))),
                ('active_time', models.DurationField(default=datetime.timedelta(days=30))),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
