# Generated by Django 3.2 on 2021-06-20 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='movie',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
    ]
