# Generated by Django 3.2 on 2021-06-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_code_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='static/main/placeholder.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='movie',
            name='price',
            field=models.TextField(default='100zł', max_length=6),
        ),
    ]
