# Generated by Django 3.2 on 2021-06-20 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210620_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='media/placeholder.jpg', upload_to=''),
        ),
    ]
