# Generated by Django 3.2 on 2021-06-20 08:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='date_purchased',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='placeholder.jpg', upload_to=''),
        ),
    ]
