# Generated by Django 3.2 on 2021-06-20 08:10

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210620_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='code',
            name='value',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique_for_date=datetime.timedelta(days=30)),
        ),
    ]
