# Generated by Django 3.2 on 2021-06-20 08:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210620_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie'),
        ),
        migrations.AlterField(
            model_name='code',
            name='value',
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
